---
- name: Testing andrewrothstein.coredns
  hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - name: Executing 'coredns --version'
      ansible.builtin.command: /usr/local/bin/coredns --version
      changed_when: false
      register: coredns_test_output
    - name: Output of 'coredns --version'
      ansible.builtin.debug:
        msg: '{{ coredns_test_output.stdout }}'
