---
- name: Installing andrewrothstein.unarchivedeps
  ansible.builtin.include_role:
    name: andrewrothstein.unarchivedeps
- name: Resolve platform specific vars
  ansible.builtin.include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'
- name: Check for install in {{ coredns_install_dir }}
  become: true
  ansible.builtin.stat:
    path: '{{ coredns_install_dir }}'
  changed_when: false
  register: coredns_binary
- name: Downloading and installing coredns
  when: not coredns_binary.stat.exists
  block:
    - name: Downloading {{ coredns_url }} to {{ coredns_tmp_tgz }}
      become: true
      become_user: root
      ansible.builtin.get_url:
        url: '{{ coredns_url }}'
        dest: '{{ coredns_tmp_tgz }}'
        mode: '644'
        checksum: '{{ coredns_checksum }}'
    - name: Mkdir {{ coredns_install_dir }}
      become: true
      become_user: root
      ansible.builtin.file:
        path: '{{ coredns_install_dir }}'
        mode: '755'
        state: directory
    - name: Unarchive {{ coredns_tmp_tgz }} to {{ coredns_install_dir }}
      become: true
      become_user: root
      ansible.builtin.unarchive:
        remote_src: true
        src: '{{ coredns_tmp_tgz }}'
        dest: '{{ coredns_install_dir }}'
        creates: '{{ coredns_install_exe }}'
  always:
    - name: Rm {{ coredns_tmp_tgz }}
      become: true
      become_user: root
      ansible.builtin.file:
        path: '{{ coredns_tmp_tgz }}'
        state: absent
- name: Linking {{ coredns_link }} to {{ coredns_install_exe }}
  become: true
  become_user: root
  ansible.builtin.file:
    src: '{{ coredns_install_exe }}'
    dest: '{{ coredns_link }}'
    state: link
